#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/local/lib/X11/xinit/.Xresources
sysmodmap=/usr/local/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /usr/local/lib/X11/xinit/xinitrc.d ] ; then
	for f in /usr/local/lib/X11/xinit/xinitrc.d/*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xmodmap /usr/local/lib/X11/xinit/.Xmodmap

export _JAVA_AWT_WM_NONREPARENTING=1

xcompmgr -d :0.0 &
xcompmgr -d :0.1 &
xcompmgr -d :0.3 &
gnome-volume-manager & # for mounting CDs, USB sticks, and such
terminator --display :0.0 &
terminator --display :0.1 &
terminator --display :0.3 &
chrome --display :0.2 &
pidgin --display :0.1 &
exec ck-launch-session dbus-launch awesome
